from .prompt_generator_12_columns_empty import (
    NODE_CLASS_MAPPINGS as EMPTY_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as EMPTY_DISPLAY,
)
from .prompt_generator_12_columns_prefilled import (
    NODE_CLASS_MAPPINGS as PREFILLED_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as PREFILLED_DISPLAY,
)
from .prompt_generator_12_columns_prefilledNSFW import (
    NODE_CLASS_MAPPINGS as PREFILLED_NSFW_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as PREFILLED_NSFW_DISPLAY,
)
from .prompt_generator_nsfw_action import (
    NODE_CLASS_MAPPINGS as NSFW_ACTION_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as NSFW_ACTION_DISPLAY,
)
from .prompt_generator_random_sections import (
    NODE_CLASS_MAPPINGS as RANDOM_SECTIONS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as RANDOM_SECTIONS_DISPLAY,
)

NODE_CLASS_MAPPINGS = {
    **EMPTY_MAPPINGS,
    **PREFILLED_MAPPINGS,
    **PREFILLED_NSFW_MAPPINGS,
    **NSFW_ACTION_MAPPINGS,
    **RANDOM_SECTIONS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **EMPTY_DISPLAY,
    **PREFILLED_DISPLAY,
    **PREFILLED_NSFW_DISPLAY,
    **NSFW_ACTION_DISPLAY,
    **RANDOM_SECTIONS_DISPLAY,
}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']